<a href="https://colab.research.google.com/github/ParnianH98/CSP-back-tracking/blob/main/City_coloring_CSP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

global var

In [ ]:
n=6
color_num=3
### matrix as a graph
graph=np.zeros((n,n))
### color of vertice number i
### zero means not colored yet
color=np.zeros(n)

generate a random n*n symmetric binary matrix

In [ ]:
def gen_random_symmetric_binary_mat():
  ### generate n*n random binary matrix
  mat = np.random.randint(2,size=(n,n))
  ### return symmetric
  return (mat+mat.T)%2

to check if to vertices are connected, the colors are the same(fail condition)
or not

In [ ]:
def ISuitAble():
    for i in range(n):
        for j in range(i + 1, n):
            ### if graph[i][j] != 0 and the values are equal, the graph is not IISuitAble
            ### the row i and col j are two connected vertices
            ### so their color should be different
            if (graph[i][j] and color[i] == color[j]):
                return False
    return True

step by step color nodes by the first color which does not exist in it's neighbours

In [ ]:
def coloring(colN, index):
   
    ### all vertices are colored
    if (index == n):
        ## if the coloring is suitable
        if (ISuitAble()):
            print("Vertice colors by order, are:")
            print(color)
            return True
        return False
 
    ### colors are diff numbers from 1 to colN
    for i in range(1, colN+1):
        color[index] = i
 
        ### to check if this color fits or should be changed
        if (coloring(colN, index + 1)):
            return True
        ### if the color does not fit, cange it to the next color
        color[index] = 0
    return False

codes starts there

In [ ]:
graph = gen_random_symmetric_binary_mat()
print(graph)
if (not coloring(color_num, 0)):
        print ("Solution does not exist")

[[0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [1 0 0 1 1 0]
 [1 0 1 0 1 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]]
Vertice colors by order, are:
[1. 1. 2. 3. 1. 1.]
