<a href="https://colab.research.google.com/github/ParnianH98/CSP-back-tracking/blob/main/N_Queen_CSP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

In [ ]:
n=8
### matrix as the game board
board = np.zeros((n,n))


In [ ]:
def ISuitAble(index, col):

    ## no need for columnal checking
    ## to check row threating
    for i in range(col):
        if board[index][i] == 1:
            return False

    ## to check diagonal ...
    for j in range(col):
        for i in range(n):
            if board[i][j] == 1 and ((i-index == j-col) or (index-i == j-col)):
                return False
  
    return True

In [ ]:
def Queen_setting(col):
   
    ### all vertices are colored
    if (col == n):
        ## if the setting is suitable
        return True
 
    for i in range(n):
        if ISuitAble(i, col):
            board[i][col] = 1
 
            if Queen_setting(col+1) == True:
                return True
  
                # If placing queen in board[i][col
                # doesn't lead to a solution, then
                # queen from board[i][col]
        board[i][col] = 0
  
    # if the queen can not be placed in any row in
    # this colum col  then return false
    return False

In [ ]:
if Queen_setting(0) == False:
    print("Solution does not exist")
print(board)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
